#!/bin/bash

pushd "$HOME/.dotfiles"

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,zsh,tmux"
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -v -R -t "$HOME" "$folder"
done
popd
